Vanila API ITCase
eo-cqrs/eo-kafka pull request #286
Opened 2023-05-03 16:27 UTC by h1alexbel

closes #236

---

## PR-Codex overview
This PR adds two to-do comments regarding missing functionality in the codebase, and adds two dependencies to the `pom.xml` file. It also adds several new tests, including one that sends a message to Kafka and verifies that it was received.

### Detailed summary
- Adds `@todo` comments for missing functionality in `Producer` and `KfConsumer` classes
- Adds `assertj-core` and `duct-tape` dependencies to `pom.xml`
- Adds new tests for `EntryTest` class, including one that sends and verifies a message to Kafka

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

2023-05-03 16:30 UTC, h1alexbel commented
peer review. @l3r8yJ take a look, please

2023-05-03 16:32 UTC, zoeself commented
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-05-06T16:32:18.284543``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

2023-05-03 16:43 UTC, l3r8yJ requested changes
@h1alexbel take a look at my comments, please

2023-05-03 16:43 UTC, l3r8yJ commented on src/it/producer-consumer-api/src/test/java/EntryTest.java
> +//    .withEmbeddedZookeeper();
comments like that are not the best thing in the repository

2023-05-03 16:43 UTC, l3r8yJ commented on src/it/producer-consumer-api/src/test/java/EntryTest.java
> +//    final Producer<String, String> producer =
Same here

2023-05-03 16:43 UTC, l3r8yJ commented on src/it/producer-consumer-api/src/test/java/EntryTest.java
> +//    consumer.subscribe("TEST-TOPIC");
Same here

2023-05-03 16:43 UTC, l3r8yJ commented on src/it/producer-consumer-api/src/test/java/EntryTest.java
> +//    producer.close();
Same here

2023-05-03 16:48 UTC, h1alexbel commented
@l3r8yJ done

2023-05-03 21:07 UTC, l3r8yJ approved these changes
@h1alexbel lgtm

2023-05-04 04:45 UTC, h1alexbel commented
@rultor merge

2023-05-04 04:47 UTC, rultor commented
> @rultor merge 

@h1alexbel OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/31836-1534089022)

2023-05-04 04:48 UTC, merged

2023-05-04 04:49 UTC, rultor commented
> @rultor merge 

@h1alexbel Done! FYI, the full log is [here](https://www.rultor.com/t/31836-1534089022) (took me 2min)

2023-05-04 05:11 UTC, zoeself commented
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).