Small fixes
eo-cqrs/eo-kafka pull request #46
Opened 2023-02-25 03:01 UTC by l3r8yJ

here some improvements, @h1alexbel take a look, please 
I also moved the fake package to the test directory because I think it was created for testing.

2023-02-25 07:29 UTC, h1alexbel requested changes

2023-02-25 07:29 UTC, h1alexbel commented on src/test/java/fake/FkProducer.java
> +package fake;
The idea was to build fake producers, consumers to use them as [Fake objects](https://www.yegor256.com/2014/09/23/built-in-fake-objects.html) in tests, in order to don't mock. Not only in our project, but in projects where we will add eo-kafka dependency.

Like jcabi-github does: https://github.com/jcabi/jcabi-github/tree/master/src/main/java/com/jcabi/github/mock

2023-02-25 09:54 UTC, l3r8yJ commented
@h1alexbel take a look, please

2023-02-25 11:36 UTC, h1alexbel approved these changes

2023-02-25 11:37 UTC, merged

2023-02-25 11:37 UTC, 0pdd commented
@l3r8yJ the puzzle [#47](https://github.com/eo-cqrs/eo-kafka/issues/47) is still not solved.

2023-02-25 11:37 UTC, h1alexbel commented
@l3r8yJ thanks!

2023-03-08 15:55 UTC, 0pdd commented
@l3r8yJ the puzzle [#98](https://github.com/eo-cqrs/eo-kafka/issues/98) is still not solved; solved: [#47](https://github.com/eo-cqrs/eo-kafka/issues/47).

2023-03-14 17:33 UTC, 0pdd commented
@l3r8yJ the puzzle [#111](https://github.com/eo-cqrs/eo-kafka/issues/111) is still not solved; solved: [#47](https://github.com/eo-cqrs/eo-kafka/issues/47), [#98](https://github.com/eo-cqrs/eo-kafka/issues/98).

2023-04-24 18:06 UTC, 0pdd commented
@l3r8yJ all 3 puzzles are solved here: [#111](https://github.com/eo-cqrs/eo-kafka/issues/111), [#47](https://github.com/eo-cqrs/eo-kafka/issues/47), [#98](https://github.com/eo-cqrs/eo-kafka/issues/98).